landing page
DSC-VJTI/CA-Website pull request #11
Opened 2021-03-02 14:39 UTC by thedarkdivinity

made a landing page.Images are random as of now but when i'll get images from the client,I'll update

2021-03-03 12:22 UTC, ShubhankarKG requested changes
Thanks! The UI is fantastic, apart from the inline changes suggested, it would be much better if we split up App.css into multiple css files, so that the css used for About is in About.css, and so on.

2021-03-03 12:22 UTC, ShubhankarKG commented on client/src/components/landingpage/AniCard.js
> +export default function AniCard({number}) {
Is the `number` prop required? It didn't have any use in the component, so we can safely remove it.

2021-03-06 12:32 UTC, thedarkdivinity commented on client/.eslintcache
> +[{"/home/sayush/Desktop/CA-Website/client/src/index.js":"1","/home/sayush/Desktop/CA-Website/client/src/reportWebVitals.js":"2","/home/sayush/Desktop/CA-Website/client/src/App.js":"3","/home/sayush/D
yes shubhankar understood

2021-03-17 04:14 UTC, BhavyaSheth22 commented
Closing as changes included in pr #29

2021-03-17 04:14 UTC, closed without merging