Added admin routes
DSC-VJTI/CA-Website pull request #20
Opened 2021-03-09 08:35 UTC by pal-16

The commit includes routes for (verified via postman)

- Creating Product
- Editing Product
- Deleting Product
- Retrieving Users

Kindly let me know if any changes to be made.

2021-03-09 09:45 UTC, pal-16 commented
Middleware left to be added.

2021-03-09 14:59 UTC, BhavyaSheth22 requested changes
Thanks for this! Please add the isAdmin middleware. Apart from that, just a few changes:

2021-03-09 14:59 UTC, BhavyaSheth22 commented on server/src/controllers/admin.controller.ts
> +  },
Where is this next function passing parameters to? If not required, I think we can remove them from all the controller functions

2021-03-09 14:59 UTC, BhavyaSheth22 commented on server/tsconfig.json
> +    "noImplicitAny": false,
Please change this to true once type checks for next are added.

2021-03-10 05:08 UTC, pal-16 commented on server/src/controllers/admin.controller.ts
> +    next
Yes, I have removed that and added a status code of 500 in case of any error caught.

2021-03-10 09:05 UTC, ShubhankarKG requested changes
Thanks, when using `async/ await`, there's no need for promises again, and vice versa.

2021-03-11 10:21 UTC, ShubhankarKG approved these changes

2021-03-11 12:54 UTC, pal-16 reviewed
I am refactoring the routes and removing the extra function. Thanks for the edit.

2021-03-11 14:46 UTC, BhavyaSheth22 approved these changes
LGTM. Thanks!

2021-03-11 14:47 UTC, merged