Applied the orange them to certain pages
DSC-VJTI/CA-Website pull request #43
Opened 2021-03-25 17:56 UTC by AMMAR-62

Some merge conflicts may occur

2021-03-25 18:01 UTC, AMMAR-62 commented
![image](https://user-images.githubusercontent.com/53120491/112521037-0dd27400-8dc2-11eb-97ad-89523b5cfbd1.png)
@classes
![image](https://user-images.githubusercontent.com/53120491/112521093-1e82ea00-8dc2-11eb-9bcf-0cca0bb2a149.png)
@Resources
![image](https://user-images.githubusercontent.com/53120491/112521160-335f7d80-8dc2-11eb-820b-1cc19d287cc2.png)
@Cart

2021-03-26 04:45 UTC, ShubhankarKG requested changes
Thanks, only cleanup required.

Please re-add the `server/.mocharc.yml` file as that is needed.

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Product Page/Product_materials/CourseContents.js
> +    // position: "static",
Please remove the comments

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Product Page/Product_materials/CourseContents.js
> +    // border: "1px outset",
Please remove the comment

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Product Page/Product_materials/CoursePageHeader.js
> +    // boxShadow: "4px 4px ",
Please remove the comment

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Product Page/Product_materials/CoursePageHeader.js
> +    // color: "#f26522",
Please remove the comment

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Product Page/Product_materials/CourseTypePane.js
> +    // boxShadow: "3px 3px"
Please remove the comment

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Resource Page/ClassPane/ClassPane.js
> +          style={{}}
Please remove the style if not needed

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Resource Page/ClassPane/Product.js
> +    // border:"2px",
Please remove the comment

2021-03-26 04:45 UTC, ShubhankarKG commented on client/src/components/Resource Page/ClassesPane.js
> +// import { Product } from "./ProductsFetcher";
Please remove the comment

2021-03-27 05:27 UTC, pal-16 commented
> Please re-add the `server/.mocharc.yml` file as that is needed.

Thanks for the changes. Just the above file needs to be added.

2021-03-28 11:34 UTC, ShubhankarKG approved these changes

2021-03-28 11:34 UTC, merged