Fetched product data from product route and filtered
DSC-VJTI/CA-Website pull request #51
Opened 2021-03-30 13:35 UTC by thedarkdivinity

Implemented fetch products and filtering

2021-03-31 01:59 UTC, ShubhankarKG requested changes

2021-03-31 06:25 UTC, thedarkdivinity commented on client/src/components/Resource Page/ClassPane/ClassPane.js
> +    console.log(innerProduct.data.data);
yes it's not needed. Removing

2021-03-31 06:25 UTC, thedarkdivinity commented on client/src/components/Resource Page/ClassPane/ClassPane.js
> +            if (prod.type === "test series") {
Sure

2021-04-03 07:09 UTC, pal-16 approved these changes
LGTM, Thanks

2021-04-03 07:09 UTC, merged