Made UI Modification In Login Register and Footer
DSC-VJTI/CA-Website pull request #53
Opened 2021-04-01 08:08 UTC by Tejas2909

2021-04-01 11:12 UTC, ShubhankarKG requested changes

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/Footer/Footer.jsx
> +            </a>
Please update all these `<a>` with `<Link>` tags

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Login.jsx
> +                </FormControl> */}
Please remove the comment if not needed

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Login.jsx
> +                      // marginTop: "1rem",
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Login.jsx
> +                </Button> */}
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +  // Input,
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +  // Button,
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +                </FormControl> */}
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +                {/* </div> */}
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +                </FormControl> */}
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +                    // marginTop: "1rem",
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +                {/* <Button
Please remove the comment if not needed.

2021-04-01 11:12 UTC, ShubhankarKG commented on client/src/components/LoginRegister/Registration.jsx
> +                {/* </div> */}
Please remove the comment if not needed.

2021-04-02 10:15 UTC, BhavyaSheth22 reviewed
![Screenshot from 2021-04-02 15-39-25](https://user-images.githubusercontent.com/60400357/113407049-33ffa180-93ca-11eb-9540-a615e31cd974.png)

The home page animations are not appearing after this PR. Can you please resolve them?

2021-04-02 12:02 UTC, Tejas2909 commented
Made all the Changes

2021-04-02 14:31 UTC, BhavyaSheth22 commented
One final change, the error msg and validation for login form doesn't show up. Please rectify that

2021-04-03 09:56 UTC, Tejas2909 commented
Done!

2021-04-03 14:00 UTC, BhavyaSheth22 approved these changes

2021-04-03 14:02 UTC, merged